<a href="https://colab.research.google.com/github/gsangf10/Analysis_Algorithm/blob/main/Logistic_Regression_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 꽃의 품종 판별


In [ ]:
from sklearn.datasets import load_iris

iris = load_iris()

# 데이터
i_data = iris.data

# 특성(feature)
feature = iris.feature_names

# 타겟(target)
target = iris.target

# 타겟의 이름
target_name = iris.target_names

# 붓꽃 품종 판별하기
# 아래와 같이 데이터가 있을 때 로지스틱 회귀를 이용해 각각 어떤 품종인지 판별하고 확률이 얼마인지 출력해주세요.

t_list = [[6.1,  3,  4.9, 1.8], [4.8, 3.4, 1.6, 0.2 ], [5.7, 3.8, 1.7, 0.3 ], [5.7, 2.8, 4.5, 1.3 ], [5.8, 2.7, 3.9, 1.2]]


# 데이터 처리

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

train_d, test_d, train_t, test_t = train_test_split(i_data, target, random_state=42)

ss = StandardScaler()
ss.fit(train_d)
train_ds = ss.transform(train_d)
test_ds = ss.transform(test_d)
ts_list = ss.transform(t_list)

ts_list


array([[ 0.33066442, -0.09232969,  0.63260689,  0.7866092 ],
       [-1.26353226,  0.8268637 , -1.27761783, -1.3621769 ],
       [-0.15985763,  1.7460571 , -1.21973223, -1.22787777],
       [-0.15985763, -0.55192639,  0.4010645 ,  0.11511354],
       [-0.03722712, -0.78172474,  0.05375091, -0.01918559]])

# Logistic Regression (로지스틱 회귀 분석)

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()

lr.max_iter = 1000 # 반복횟수
lr.C = 20 # 규제 파라미터

lr.fit(train_ds, train_t)
lr.score(train_ds, train_t), lr.score(test_ds, test_t)

print(lr.predict(ts_list)) # 확률에 의한 추정되는 특성
print(np.round(lr.predict_proba(ts_list), decimals=3)) # 각 특성에 대한 확률
print(target_name)

[2 0 0 1 1]
[[0.    0.318 0.682]
 [0.999 0.001 0.   ]
 [0.995 0.005 0.   ]
 [0.001 0.983 0.016]
 [0.002 0.998 0.001]]
['setosa' 'versicolor' 'virginica']
